---
# tasks file for jsbattle

  - name: Install epel
    shell: curl -sL https://rpm.nodesource.com/setup_8.x | bash -
    args:
      warn: False

  - name: Install nodejs
    yum: name=nodejs

  - name: Install git
    yum:
      name: git

  - name: Add app user
    user:
      name: "{{ jsbattle_user }}"

  - name: Clean app path
    file:
      state: absent
      path: "{{ jsbattle_home }}/jsbattle"

  - name: Create app directory
    file:
      path: "{{ jsbattle_home }}/jsbattle"
      state: directory
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: Get JsBattle from GitHub
    git:
      repo: https://github.com/jamro/jsbattle.git
      dest: "{{ jsbattle_home }}/jsbattle"
      version: "{{ jsbattle_version }}"
      force: yes
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: Install dependencies
    command: npm install --unsafe-perm=true --allow-root
    args:
      chdir: "{{ jsbattle_home }}/jsbattle"
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: build
    command: npm run build
    args:
      chdir: "{{ jsbattle_home }}/jsbattle"
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: deploy APP ecosystem config
    template:
      src: ecosystem.config.js
      dest: "{{ jsbattle_home }}/jsbattle/packages/jsbattle/dist/ecosystem.config.js"
      owner: "{{ jsbattle_user }}"
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: Stop APP
    shell: "npm stop || true"
    args:
      chdir: "{{ jsbattle_home }}/jsbattle"
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: Start APP
    shell: "npm start || true"
    args:
      chdir: "{{ jsbattle_home }}/jsbattle"
    become: yes
    become_user: "{{ jsbattle_user }}"
