---
# tasks file for jsbattle

  - name: Install epel
    shell: curl -sL https://rpm.nodesource.com/setup_8.x | bash -
    args:
      warn: False

  - name: Install nodejs
    yum: name=nodejs

  - name: Add app user
    user:
      name: "{{ jsbattle_user }}"

  - name: Create app directory
    file:
      path: "{{ jsbattle_home }}/jsbattle"
      state: directory
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: Get JsBattle from npm
    npm:
      name: jsbattle
      path:  "{{ jsbattle_home }}/jsbattle"
      version: "{{ jsbattle_version }}"
    become: yes
    become_user: "{{ jsbattle_user }}"

  - name: copy service runner
    template:
      src: jsbattle.sh
      dest: "{{ jsbattle_home }}/jsbattle/jsbattle.sh"
      mode: 0755

  - name: copy service definition
    template:
      src: jsbattle.service
      dest: "/usr/lib/systemd/system/jsbattle.service"
      mode: 0755

  - name: start service
    systemd:
      state: restarted
      daemon_reload: yes
      name: jsbattle
      enabled: yes
